export const MARCAS = [
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "Genesis",
  "Hino",
  "Honda",
  "Hyundai",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mini Cooper",
  "Mitsubishi",
  "Nissan",
  "Peugeot",
  "Porsche",
  "Ram",
  "Renault",
  "Rolls-Royce",
  "Seat",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo"
].sort();

export const MODELOS_BY_MARCA = {
  "Alfa Romeo": ["Giulia", "Stelvio", "4C"],
  "Aston Martin": ["DB11", "DBS", "Vantage", "Valhalla"],
  "Audi": ["A3", "A4", "A6", "A8", "Q5", "Q7", "Q8"],
  "Bentley": ["Continental GT", "Flying Spur", "Bentayga"],
  "BMW": ["Serie 1", "Serie 3", "Serie 5", "Serie 7", "X3", "X5", "i3", "i8"],
  "Bugatti": ["Chiron", "Veyron", "Bolide"],
  "Cadillac": ["Escalade", "XT4", "XT5", "XT6"],
  "Chevrolet": ["Camaro", "Cruze", "Onix", "Tracker", "Silverado"],
  "Chrysler": ["300", "Pacifica", "Voyager"],
  "Citroen": ["C3", "C4", "C5 Aircross", "Berlingo"],
  "Dodge": ["Charger", "Challenger", "Durango", "Journey"],
  "Ferrari": ["488", "F8 Tributo", "Roma", "SF90 Stradale", "Purosangue"],
  "Fiat": ["500", "500X", "Uno", "Cronos", "Tipo"],
  "Ford": ["Fiesta", "Focus", "Mondeo", "Mustang", "F-150", "Explorer"],
  "Genesis": ["G70", "G80", "G90", "GV70", "GV80"],
  "Hino": ["Chronos"],
  "Honda": ["Civic", "Accord", "Fit", "HR-V", "CR-V", "Pilot"],
  "Hyundai": ["i10", "i20", "i30", "Kona", "Tucson", "Santa Fe", "Elantra"],
  "Isuzu": ["D-Max"],
  "Jaguar": ["XE", "XF", "XJ", "F-Type", "E-Pace"],
  "Jeep": ["Cherokee", "Compass", "Renegade", "Wrangler"],
  "Kia": ["Rio", "Ceed", "Sportage", "Sorento", "Stinger"],
  "Lamborghini": ["Aventador", "Huracán", "Urus", "Revuelto"],
  "Land Rover": ["Defender", "Discovery", "Range Rover", "Range Rover Evoque", "Range Rover Sport"],
  "Lexus": ["IS", "ES", "RX", "NX", "LX"],
  "Lincoln": ["Navigator"],
  "Maserati": ["Ghibli", "Levante", "Quattroporte", "MC20"],
  "Mazda": ["Mazda3", "Mazda6", "CX-3", "CX-5", "MX-5 Miata"],
  "McLaren": ["720S", "Artura", "Speedtail"],
  "Mercedes-Benz": ["Clase A", "Clase C", "Clase E", "Clase S", "GLA", "GLC"],
  "Mini Cooper": ["3-Door", "5-Door", "Clubman", "Countryman", "Convertible"],
  "Mitsubishi": ["Lancer", "Outlander", "Eclipse Cross", "ASX", "Pajero"],
  "Nissan": ["Sentra", "Altima", "Versa", "Patrol", "X-Trail", "GT-R"],
  "Peugeot": ["206", "207", "208", "3008", "5008", "308"],
  "Porsche": ["911", "Cayenne", "Panamera", "Macan", "Porsche Taycan"],
  "Ram": ["1500", "2500", "3500", "ProMaster"],
  "Renault": ["Clio", "Megane", "Duster", "Koleos", "Captur"],
  "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Cullinan"],
  "Seat": ["Ibiza", "Leon", "Arona", "Ateca", "Toledo"],
  "Subaru": ["Impreza", "Outback", "Forester", "BRZ", "WRX"],
  "Suzuki": ["Swift", "Vitara", "Jimny"],
  "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Roadster"],
  "Toyota": ["Corolla", "Camry", "Hilux", "RAV4", "Yaris", "Tacoma", "Prius"],
  "Volkswagen": ["Golf", "Passat", "Polo", "Jetta", "ID.4", "Touareg"],
  "Volvo": ["S60", "S90", "V60", "XC40", "XC60", "XC90"]
};
