export const MARCAS = [
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "Genesis",
  "Hino",
  "Honda",
  "Hyundai",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mini Cooper",
  "Mitsubishi",
  "Nissan",
  "Peugeot",
  "Porsche",
  "Ram",
  "Renault",
  "Rolls-Royce",
  "Seat",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo"
].sort();

export const MODELOS_BY_MARCA = {
  "Alfa Romeo": ["4C", "Giulia", "Stelvio"],
  "Aston Martin": ["DB11", "DBS", "Valhalla", "Vantage"],
  "Audi": ["A3", "A4", "A6", "A8", "Q5", "Q7", "Q8"],
  "Bentley": ["Bentayga", "Continental GT", "Flying Spur"],
  "BMW": ["Serie 1", "Serie 3", "Serie 5", "Serie 7", "X3", "X5", "i3", "i8"],
  "Bugatti": ["Bolide", "Chiron", "Veyron"],
  "Cadillac": ["Escalade", "XT4", "XT5", "XT6"],
  "Chevrolet": ["Aveo", "Blazer", "Camaro", "Corsa", "Cruze", "Montana", "Onix", "Prisma", "S-10", "Spin", "Tracker"],
  "Chrysler": ["300", "Pacifica", "Voyager"],
  "Citroen": ["Berlingo", "C3", "C3 Aircross", "C4", "C4 Lounge", "C5"],
  "Dodge": ["Challenger", "Charger", "Durango", "Journey"],
  "Ferrari": ["488", "F8 Tributo", "Purosangue", "Roma", "SF90 Stradale"],
  "Fiat": ["500", "Argo", "Cronos", "Ducato", "Fiorino", "Idea", "Linea", "Mobi", "Palio", "Siena", "Strada", "Toro", "Uno"],
  "Ford": ["EcoSport", "Edge", "Fiesta", "Focus", "Ka", "Kuga", "Mondeo", "Mustang", "Ranger", "Territory", "Transit"],
  "Genesis": ["G70", "G80", "G90", "GV70", "GV80"],
  "Hino": ["Chronos"],
  "Honda": ["Accord", "Civic", "CR-V", "Fit", "HR-V", "Pilot"],
  "Hyundai": ["Elantra", "i10", "i20", "i30", "Kona", "Santa Fe", "Tucson"],
  "Isuzu": ["D-Max"],
  "Jaguar": ["E-Pace", "F-Type", "XE", "XF", "XJ"],
  "Jeep": ["Cherokee", "Compass", "Renegade", "Wrangler"],
  "Kia": ["Ceed", "Rio", "Sorento", "Sportage", "Stinger"],
  "Lamborghini": ["Aventador", "Huracán", "Revuelto", "Urus"],
  "Land Rover": ["Defender", "Discovery", "Range Rover", "Range Rover Evoque", "Range Rover Sport"],
  "Lexus": ["ES", "IS", "LX", "NX", "RX"],
  "Lincoln": ["Navigator"],
  "Maserati": ["Ghibli", "Levante", "MC20", "Quattroporte"],
  "Mazda": ["CX-3", "CX-5", "Mazda3", "Mazda6", "MX-5 Miata"],
  "McLaren": ["720S", "Artura", "Speedtail"],
  "Mercedes-Benz": ["Clase A", "Clase C", "Clase E", "Clase S", "GLA", "GLC"],
  "Mini Cooper": ["3-Door", "5-Door", "Clubman", "Convertible", "Countryman"],
  "Mitsubishi": ["ASX", "Eclipse Cross", "Lancer", "Outlander", "Pajero"],
  "Nissan": ["Altima", "GT-R", "Patrol", "Sentra", "Versa", "X-Trail"],
  "Peugeot": ["2008", "206", "207", "208", "3008", "307", "308", "308S", "407", "408", "5008", "504", "Partner"],
  "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Porsche Taycan"],
  "Ram": ["1500", "2500", "3500", "ProMaster"],
  "Renault": ["Captur", "Clio", "Duster", "Fluence", "Kangoo", "Koleos", "Logan", "Meganè", "Oroch", "Sandero", "Stepway", "Symbol", "Zoe"],
  "Rolls-Royce": ["Cullinan", "Ghost", "Phantom", "Wraith"],
  "Seat": ["Ateca", "Arona", "Ibiza", "Leon", "Toledo"],
  "Subaru": ["BRZ", "Forester", "Impreza", "Outback", "WRX"],
  "Suzuki": ["Fun", "Jimny", "Swift", "Vitara"],
  "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Roadster"],
  "Toyota": ["C-HR", "Camry", "Corolla", "Etios", "Hilux", "Land Cruiser", "Prius", "RAV4", "SW4", "Yaris"],
  "Volkswagen": ["Amarok", "Bora", "Fox", "Gol", "Gol Trend", "Golf",  "Passat", "Polo", "Surán", "T-Cross", "Tiguan", "Up", "Vento", "Voyage"],
  "Volvo": ["S60", "S90", "V60", "XC40", "XC60", "XC90"]
};
